// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/port_service.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取随机端口请求
type GetRandomPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomPortRequest) Reset() {
	*x = GetRandomPortRequest{}
	mi := &file_proto_port_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomPortRequest) ProtoMessage() {}

func (x *GetRandomPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomPortRequest.ProtoReflect.Descriptor instead.
func (*GetRandomPortRequest) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{0}
}

// 获取随机端口响应
type GetRandomPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`  // 端口号
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomPortResponse) Reset() {
	*x = GetRandomPortResponse{}
	mi := &file_proto_port_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomPortResponse) ProtoMessage() {}

func (x *GetRandomPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomPortResponse.ProtoReflect.Descriptor instead.
func (*GetRandomPortResponse) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomPortResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetRandomPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取N个随机端口请求
type GetRandomPortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 需要获取的端口数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomPortsRequest) Reset() {
	*x = GetRandomPortsRequest{}
	mi := &file_proto_port_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomPortsRequest) ProtoMessage() {}

func (x *GetRandomPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomPortsRequest.ProtoReflect.Descriptor instead.
func (*GetRandomPortsRequest) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetRandomPortsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取N个随机端口响应
type GetRandomPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []int32                `protobuf:"varint,1,rep,packed,name=ports,proto3" json:"ports,omitempty"` // 端口数组
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`         // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomPortsResponse) Reset() {
	*x = GetRandomPortsResponse{}
	mi := &file_proto_port_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomPortsResponse) ProtoMessage() {}

func (x *GetRandomPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomPortsResponse.ProtoReflect.Descriptor instead.
func (*GetRandomPortsResponse) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetRandomPortsResponse) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *GetRandomPortsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取APP端口请求
type GetAppPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"` // APP名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppPortRequest) Reset() {
	*x = GetAppPortRequest{}
	mi := &file_proto_port_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppPortRequest) ProtoMessage() {}

func (x *GetAppPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppPortRequest.ProtoReflect.Descriptor instead.
func (*GetAppPortRequest) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppPortRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// 获取APP端口响应
type GetAppPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`  // 端口号
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppPortResponse) Reset() {
	*x = GetAppPortResponse{}
	mi := &file_proto_port_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppPortResponse) ProtoMessage() {}

func (x *GetAppPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppPortResponse.ProtoReflect.Descriptor instead.
func (*GetAppPortResponse) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppPortResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetAppPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 设置APP端口请求
type SetAppPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"` // APP名称
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                     // 端口号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppPortRequest) Reset() {
	*x = SetAppPortRequest{}
	mi := &file_proto_port_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppPortRequest) ProtoMessage() {}

func (x *SetAppPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppPortRequest.ProtoReflect.Descriptor instead.
func (*SetAppPortRequest) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetAppPortRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *SetAppPortRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// 设置APP端口响应
type SetAppPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppPortResponse) Reset() {
	*x = SetAppPortResponse{}
	mi := &file_proto_port_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppPortResponse) ProtoMessage() {}

func (x *SetAppPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppPortResponse.ProtoReflect.Descriptor instead.
func (*SetAppPortResponse) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetAppPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 快速设置APP端口请求
type QuickSetAppPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"` // APP名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickSetAppPortRequest) Reset() {
	*x = QuickSetAppPortRequest{}
	mi := &file_proto_port_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickSetAppPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickSetAppPortRequest) ProtoMessage() {}

func (x *QuickSetAppPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickSetAppPortRequest.ProtoReflect.Descriptor instead.
func (*QuickSetAppPortRequest) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{8}
}

func (x *QuickSetAppPortRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// 快速设置APP端口响应
type QuickSetAppPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`  // 端口号
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickSetAppPortResponse) Reset() {
	*x = QuickSetAppPortResponse{}
	mi := &file_proto_port_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickSetAppPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickSetAppPortResponse) ProtoMessage() {}

func (x *QuickSetAppPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickSetAppPortResponse.ProtoReflect.Descriptor instead.
func (*QuickSetAppPortResponse) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{9}
}

func (x *QuickSetAppPortResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *QuickSetAppPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 删除APP端口请求
type DeleteAppPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"` // APP名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppPortRequest) Reset() {
	*x = DeleteAppPortRequest{}
	mi := &file_proto_port_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppPortRequest) ProtoMessage() {}

func (x *DeleteAppPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppPortRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppPortRequest) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAppPortRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// 删除APP端口响应
type DeleteAppPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppPortResponse) Reset() {
	*x = DeleteAppPortResponse{}
	mi := &file_proto_port_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppPortResponse) ProtoMessage() {}

func (x *DeleteAppPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_port_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppPortResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppPortResponse) Descriptor() ([]byte, []int) {
	return file_proto_port_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAppPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_port_service_proto protoreflect.FileDescriptor

const file_proto_port_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/port_service.proto\x12\fport_service\"\x16\n" +
	"\x14GetRandomPortRequest\"A\n" +
	"\x15GetRandomPortResponse\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15GetRandomPortsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"D\n" +
	"\x16GetRandomPortsResponse\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\x05R\x05ports\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x11GetAppPortRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\">\n" +
	"\x12GetAppPortResponse\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\x11SetAppPortRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"*\n" +
	"\x12SetAppPortResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"3\n" +
	"\x16QuickSetAppPortRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\"C\n" +
	"\x17QuickSetAppPortResponse\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x14DeleteAppPortRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\"-\n" +
	"\x15DeleteAppPortResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xa0\x04\n" +
	"\vPortService\x12X\n" +
	"\rGetRandomPort\x12\".port_service.GetRandomPortRequest\x1a#.port_service.GetRandomPortResponse\x12[\n" +
	"\x0eGetRandomPorts\x12#.port_service.GetRandomPortsRequest\x1a$.port_service.GetRandomPortsResponse\x12O\n" +
	"\n" +
	"GetAppPort\x12\x1f.port_service.GetAppPortRequest\x1a .port_service.GetAppPortResponse\x12O\n" +
	"\n" +
	"SetAppPort\x12\x1f.port_service.SetAppPortRequest\x1a .port_service.SetAppPortResponse\x12^\n" +
	"\x0fQuickSetAppPort\x12$.port_service.QuickSetAppPortRequest\x1a%.port_service.QuickSetAppPortResponse\x12X\n" +
	"\rDeleteAppPort\x12\".port_service.DeleteAppPortRequest\x1a#.port_service.DeleteAppPortResponseB\x1cZ\x1agithub.com/JJApplication/Themis/protob\x06proto3"

var (
	file_proto_port_service_proto_rawDescOnce sync.Once
	file_proto_port_service_proto_rawDescData []byte
)

func file_proto_port_service_proto_rawDescGZIP() []byte {
	file_proto_port_service_proto_rawDescOnce.Do(func() {
		file_proto_port_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_port_service_proto_rawDesc), len(file_proto_port_service_proto_rawDesc)))
	})
	return file_proto_port_service_proto_rawDescData
}

var file_proto_port_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_port_service_proto_goTypes = []any{
	(*GetRandomPortRequest)(nil),    // 0: port_service.GetRandomPortRequest
	(*GetRandomPortResponse)(nil),   // 1: port_service.GetRandomPortResponse
	(*GetRandomPortsRequest)(nil),   // 2: port_service.GetRandomPortsRequest
	(*GetRandomPortsResponse)(nil),  // 3: port_service.GetRandomPortsResponse
	(*GetAppPortRequest)(nil),       // 4: port_service.GetAppPortRequest
	(*GetAppPortResponse)(nil),      // 5: port_service.GetAppPortResponse
	(*SetAppPortRequest)(nil),       // 6: port_service.SetAppPortRequest
	(*SetAppPortResponse)(nil),      // 7: port_service.SetAppPortResponse
	(*QuickSetAppPortRequest)(nil),  // 8: port_service.QuickSetAppPortRequest
	(*QuickSetAppPortResponse)(nil), // 9: port_service.QuickSetAppPortResponse
	(*DeleteAppPortRequest)(nil),    // 10: port_service.DeleteAppPortRequest
	(*DeleteAppPortResponse)(nil),   // 11: port_service.DeleteAppPortResponse
}
var file_proto_port_service_proto_depIdxs = []int32{
	0,  // 0: port_service.PortService.GetRandomPort:input_type -> port_service.GetRandomPortRequest
	2,  // 1: port_service.PortService.GetRandomPorts:input_type -> port_service.GetRandomPortsRequest
	4,  // 2: port_service.PortService.GetAppPort:input_type -> port_service.GetAppPortRequest
	6,  // 3: port_service.PortService.SetAppPort:input_type -> port_service.SetAppPortRequest
	8,  // 4: port_service.PortService.QuickSetAppPort:input_type -> port_service.QuickSetAppPortRequest
	10, // 5: port_service.PortService.DeleteAppPort:input_type -> port_service.DeleteAppPortRequest
	1,  // 6: port_service.PortService.GetRandomPort:output_type -> port_service.GetRandomPortResponse
	3,  // 7: port_service.PortService.GetRandomPorts:output_type -> port_service.GetRandomPortsResponse
	5,  // 8: port_service.PortService.GetAppPort:output_type -> port_service.GetAppPortResponse
	7,  // 9: port_service.PortService.SetAppPort:output_type -> port_service.SetAppPortResponse
	9,  // 10: port_service.PortService.QuickSetAppPort:output_type -> port_service.QuickSetAppPortResponse
	11, // 11: port_service.PortService.DeleteAppPort:output_type -> port_service.DeleteAppPortResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_port_service_proto_init() }
func file_proto_port_service_proto_init() {
	if File_proto_port_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_port_service_proto_rawDesc), len(file_proto_port_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_port_service_proto_goTypes,
		DependencyIndexes: file_proto_port_service_proto_depIdxs,
		MessageInfos:      file_proto_port_service_proto_msgTypes,
	}.Build()
	File_proto_port_service_proto = out.File
	file_proto_port_service_proto_goTypes = nil
	file_proto_port_service_proto_depIdxs = nil
}
